"""Add created_at and updated_at to User

Revision ID: 842db2beb4ec
Revises: 954ce9e9e29d
Create Date: 2025-06-18 19:32:08.765264

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '842db2beb4ec'
down_revision = '954ce9e9e29d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
